name: docs-verify

on:
  pull_request:
    branches:
      - master
    paths:
      # on documentation change (changelog & contribution guidlines are a part of that)
      - 'docs/**'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      # also when docstrings in the source code change
      - 'src/**'

jobs:
  docs:
    name: Generate Sphinx Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Load cached venv
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install personio-py and all dependencies
        run: |
          poetry install --no-interaction
      - name: Generate Sphinx Documentation
        run: |
          set -uex
          source .venv/bin/activate
          cd docs
          make html SPHINXOPTS="-W --keep-going -n"
      - uses: actions/upload-artifact@v2
        with:
          name: sphinx-docs
          path: docs/build/html/
